OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Models/Album.cs
// <copyright file="Album.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace AlbumOfTheYear.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Album Model in WebApplication.
    /// </summary>
    public class Album
    {
        /// <summary>
        /// Gets or sets the id of the album.
        /// </summary>
        [Display(Name = "Album Id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the album.
        /// </summary>
        [Display(Name = "Album Title")]
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the genre of the album.
        /// </summary>
        [Display(Name = "Album Genre")]
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string Genre { get; set; }

        /// <summary>
        /// Gets or sets the performer of the album.
        /// </summary>
        [Display(Name = "Album Performer")]
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string Performer { get; set; }

        /// <summary>
        /// Gets or sets the release year of the album.
        /// </summary>
        [Display(Name = "Album Release Year")]
        [Range(1900, 2022)]
        [Required]
        public int ReleaseYear { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the albumee is a reissue or not..
        /// </summary>
        [Display(Name = "Album Reissueness")]
        [Required]
        public bool IsReissue { get; set; }
    }
}

OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Controllers/AlbumsController.cs
// <copyright file="AlbumsController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace AlbumOfTheYear.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AlbumOfTheYear.Logic;
    using AlbumOfTheYear.Web.Models;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Controller of the WebApplication.
    /// </summary>
    public class AlbumsController : Controller
    {
        private IAlbumLogic logic;
        private IMapper mapper;
        private AlbumListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="AlbumsController"/> class.
        /// </summary>
        /// <param name="logic">Logic interface.</param>
        /// <param name="mapper">Mapper interface.</param>
        public AlbumsController(IAlbumLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new AlbumListViewModel();
            this.vm.EditedAlbum = new Models.Album();

            var albums = this.logic.GetAllAlbums();
            this.vm.ListOfAlbums = this.mapper.Map<IList<Data.Album>, List<Models.Album>>(albums);
        }

        /// <summary>
        /// Gets or sets the IFP.
        /// </summary>
        public IFormatProvider IFP { get; set; }

        /// <summary>
        /// Edit Action method.
        /// </summary>
        /// <returns>Action result.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("AlbumsIndex", this.vm);
        }

        /// <summary>
        /// Showing details of the album.
        /// </summary>
        /// <param name="id">Id of the album to show.</param>
        /// <returns>Action result.</returns>
        public IActionResult Details(int id)
        {
            return this.View("AlbumsDetails", this.GetAlbum(id));
        }

        /// <summary>
        /// Removing an album.
        /// </summary>
        /// <param name="id">Id of the album to remove.</param>
        /// <returns>Action result.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            if (this.logic.RemoveAlbum(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Editing an album.
        /// </summary>
        /// <param name="id">Id of the album to edit.</param>
        /// <returns>Action result.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedAlbum = this.GetAlbum(id);
            return this.View("AlbumsIndex", this.vm);
        }

        /// <summary>
        /// Editing action.
        /// </summary>
        /// <param name="album">Album to edit.</param>
        /// <param name="editAction">Action name.</param>
        /// <returns>Action result.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Album album, string editAction)
        {
            if (this.ModelState.IsValid && album != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    this.logic.AddAlbum(album.Title, album.Genre, album.Performer, album.ReleaseYear, album.IsReissue);
                }
                else
                {
                    if (!this.logic.UpdateAlbum(album.Id, new string[] { album.Title, album.Performer, album.Genre, album.ReleaseYear.ToString(this.IFP), album.IsReissue.ToString() }))
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedAlbum = album;
                return this.View("AlbumsIndex", this.vm);
            }
        }

        private Models.Album GetAlbum(int id)
        {
            Data.Album oneAlbum = this.logic.GetAlbumById(id);
            return this.mapper.Map<Data.Album, Models.Album>(oneAlbum);
        }
    }
}

OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Views/Albums/AlbumsDetails.cshtml
@model AlbumOfTheYear.Web.Models.Album

@{ 
    ViewData["Title"] = "AlbumsDetails";
}

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Performer)</td>
        <td>@Html.DisplayFor(m => m.Performer)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Title)</td>
        <td>@Html.DisplayFor(m => m.Title)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Genre)</td>
        <td>@Html.DisplayFor(m => m.Genre)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ReleaseYear)</td>
        <td>@Html.DisplayFor(m => m.ReleaseYear)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.IsReissue)</td>
        <td>@Html.DisplayFor(m => m.IsReissue)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Views/Albums/AlbumsEdit.cshtml
@model AlbumOfTheYear.Web.Models.Album

<h2>AlbumsEdit</h2>

@using (Html.BeginForm("Edit", "Albums"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Performer)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Performer)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Title)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Title)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Genre)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Genre)</div>

    <div class="editor-label">@Html.LabelFor(m => m.ReleaseYear)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ReleaseYear)</div>

    <div class="editor-label">@Html.LabelFor(m => m.IsReissue)</div>
    <div class="editor-field">@Html.EditorFor(m => m.IsReissue)</div>

    <input type="submit" value="SEND" />
}  

OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Views/Albums/AlbumsIndex.cshtml
@model AlbumOfTheYear.Web.Models.AlbumListViewModel

@{
    ViewData["Title"] = "AlbumsIndex";
}

<h2>Albums Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("AlbumsEdit", Model.EditedAlbum)

@await Html.PartialAsync("AlbumsList", Model.ListOfAlbums)

OENIK_PROG3_2020_2_DZTB0V/AlbumOfTheYear.Web/Views/Albums/AlbumsList.cshtml
@model IEnumerable<AlbumOfTheYear.Web.Models.Album>

<h2>AlbumsList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Title)</th>
            <th>@Html.DisplayNameFor(m => m.First().Performer)</th>
            <th>@Html.DisplayNameFor(m => m.First().Genre)</th>
            <th>@Html.DisplayNameFor(m => m.First().ReleaseYear)</th>
            <th>@Html.DisplayNameFor(m => m.First().IsReissue)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach(var album in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=>album.Title)</td>
                <td>@Html.DisplayFor(m=>album.Performer)</td>
                <td>@Html.DisplayFor(m=>album.Genre)</td>
                <td>@Html.DisplayFor(m=>album.ReleaseYear)</td>
                <td>@Html.DisplayFor(m=>album.IsReissue)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = album.Id})</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = album.Id})</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = album.Id})</td>
            </tr>
        }
    </table>
}